### PR TITLE
Ls styling

### PR DESCRIPTION
**Pull request by lindseysatterfield**
## Description
- added background image
- added new font
- updated home page card color
- updated button sizing

## Related Issue
#59 

## Motivation and Context
This makes the page look more user friendly and styled for a better experience.

## How Can This Be Tested?
`git fetch`
`npm start`

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by Gabrielle-Tobermann — APPROVED** [review]
Looks so good!

**Review by tsekeres — COMMENTED** [review]
👍

**Review by Greenfin17 — COMMENTED** [review]
Looks nice.

**Review by Greenfin17 — APPROVED** [review]
Looks nice.

**Pull request merged**
