### PR TITLE
setup webpack, added planning.md

### PR DESCRIPTION
**Pull request by Gabrielle-Tobermann**
Here are all the links: 

Netlify: jurassic-world-dashboard.netlify.app

Milestones: https://github.com/nss-evening-cohort-14/jurrasic-world-dashboard-jurrasic-world-dashboard/milestones

Project board: https://github.com/nss-evening-cohort-14/jurrasic-world-dashboard-jurrasic-world-dashboard/projects/1

Workflow: Workflow-Jurassic-Park

Here is an actual link to the workflow (we used Lucid charts): https://lucid.app/lucidchart/48d101fb-5c19-41c9-86aa-5155fc78248b/edit?docId=48d101fb-5c19-41c9-86aa-5155fc78248b&shared=true&page=0_0#

Wireframe: https://www.figma.com/file/031olQyE3BwuD0WJtrGIIS/Jurassic-World-Visitor?node-id=0%3A1

ERD: https://dbdiagram.io/d/604e67b4fcdcb6230b241915

### CODE REVIEW

**Comment by drteresavasquez** [comment]
@Gabrielle-Tobermann where is the deploy link so that I can test the webpack integration?

**Comment by Gabrielle-Tobermann** [comment]
@drteresavasquez I've added the Netlify link to the markdown file.

**Comment by drteresavasquez** [comment]
I see. Does this include unauthenticated users to be able to see all the details but not the ability to CUD?

**Comment by Gabrielle-Tobermann** [comment]
We have a ticket for Auth, I've added a description (Authentication for (CUD), Read-only without authentication). In our workflow diagram, all the way at the top-left, if the user is not logged in, they can only see the info (getCard() --> showCard(cardArray)).

**Comment by drteresavasquez** [comment]
Great! Once the tickets are updated, ping me in slack and I’ll take a look. Everything else looks great! You may have to make some Data modifications as you move forward but that’s not unusual as you become more clear on what your UI and backend needs are.

**Review by drteresavasquez — APPROVED** [review]
Looks good! Go forth!

**Pull request merged**
